name:                dhall-aws-cloudformation
version:             0.1.0.0
github:              "githubuser/dhall-aws-cloudformation"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dhall-aws-cloudformation#readme>

dependencies:
- base >= 4.7 && < 5
- dhall
- text
- aeson
- containers
- mtl
- bytestring
- unordered-containers
- filepath
- directory
- vector
library:
  source-dirs: src

executables:
  dhall-aws-cloudformation-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-aws-cloudformation

tests:
  dhall-aws-cloudformation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-aws-cloudformation
    - raw-strings-qq
    - HUnit
