{ Type =
    { AbsentInputAudioBehavior : Optional (./../../Fn.dhall).CfnText
    , Arib : Optional (./../../Fn.dhall).CfnText
    , AribCaptionsPid : Optional (./../../Fn.dhall).CfnText
    , AribCaptionsPidControl : Optional (./../../Fn.dhall).CfnText
    , AudioBufferModel : Optional (./../../Fn.dhall).CfnText
    , AudioFramesPerPes : Optional Integer
    , AudioPids : Optional (./../../Fn.dhall).CfnText
    , AudioStreamType : Optional (./../../Fn.dhall).CfnText
    , Bitrate : Optional Integer
    , BufferModel : Optional (./../../Fn.dhall).CfnText
    , CcDescriptor : Optional (./../../Fn.dhall).CfnText
    , DvbNitSettings : Optional (./DvbNitSettings.dhall).Type
    , DvbSdtSettings : Optional (./DvbSdtSettings.dhall).Type
    , DvbSubPids : Optional (./../../Fn.dhall).CfnText
    , DvbTdtSettings : Optional (./DvbTdtSettings.dhall).Type
    , DvbTeletextPid : Optional (./../../Fn.dhall).CfnText
    , Ebif : Optional (./../../Fn.dhall).CfnText
    , EbpAudioInterval : Optional (./../../Fn.dhall).CfnText
    , EbpLookaheadMs : Optional Integer
    , EbpPlacement : Optional (./../../Fn.dhall).CfnText
    , EcmPid : Optional (./../../Fn.dhall).CfnText
    , EsRateInPes : Optional (./../../Fn.dhall).CfnText
    , EtvPlatformPid : Optional (./../../Fn.dhall).CfnText
    , EtvSignalPid : Optional (./../../Fn.dhall).CfnText
    , FragmentTime : Optional Double
    , Klv : Optional (./../../Fn.dhall).CfnText
    , KlvDataPids : Optional (./../../Fn.dhall).CfnText
    , NielsenId3Behavior : Optional (./../../Fn.dhall).CfnText
    , NullPacketBitrate : Optional Double
    , PatInterval : Optional Integer
    , PcrControl : Optional (./../../Fn.dhall).CfnText
    , PcrPeriod : Optional Integer
    , PcrPid : Optional (./../../Fn.dhall).CfnText
    , PmtInterval : Optional Integer
    , PmtPid : Optional (./../../Fn.dhall).CfnText
    , ProgramNum : Optional Integer
    , RateMode : Optional (./../../Fn.dhall).CfnText
    , Scte27Pids : Optional (./../../Fn.dhall).CfnText
    , Scte35Control : Optional (./../../Fn.dhall).CfnText
    , Scte35Pid : Optional (./../../Fn.dhall).CfnText
    , SegmentationMarkers : Optional (./../../Fn.dhall).CfnText
    , SegmentationStyle : Optional (./../../Fn.dhall).CfnText
    , SegmentationTime : Optional Double
    , TimedMetadataBehavior : Optional (./../../Fn.dhall).CfnText
    , TimedMetadataPid : Optional (./../../Fn.dhall).CfnText
    , TransportStreamId : Optional Integer
    , VideoPid : Optional (./../../Fn.dhall).CfnText
    }
, default =
  { AbsentInputAudioBehavior = None (./../../Fn.dhall).CfnText
  , Arib = None (./../../Fn.dhall).CfnText
  , AribCaptionsPid = None (./../../Fn.dhall).CfnText
  , AribCaptionsPidControl = None (./../../Fn.dhall).CfnText
  , AudioBufferModel = None (./../../Fn.dhall).CfnText
  , AudioFramesPerPes = None Integer
  , AudioPids = None (./../../Fn.dhall).CfnText
  , AudioStreamType = None (./../../Fn.dhall).CfnText
  , Bitrate = None Integer
  , BufferModel = None (./../../Fn.dhall).CfnText
  , CcDescriptor = None (./../../Fn.dhall).CfnText
  , DvbNitSettings = None (./DvbNitSettings.dhall).Type
  , DvbSdtSettings = None (./DvbSdtSettings.dhall).Type
  , DvbSubPids = None (./../../Fn.dhall).CfnText
  , DvbTdtSettings = None (./DvbTdtSettings.dhall).Type
  , DvbTeletextPid = None (./../../Fn.dhall).CfnText
  , Ebif = None (./../../Fn.dhall).CfnText
  , EbpAudioInterval = None (./../../Fn.dhall).CfnText
  , EbpLookaheadMs = None Integer
  , EbpPlacement = None (./../../Fn.dhall).CfnText
  , EcmPid = None (./../../Fn.dhall).CfnText
  , EsRateInPes = None (./../../Fn.dhall).CfnText
  , EtvPlatformPid = None (./../../Fn.dhall).CfnText
  , EtvSignalPid = None (./../../Fn.dhall).CfnText
  , FragmentTime = None Double
  , Klv = None (./../../Fn.dhall).CfnText
  , KlvDataPids = None (./../../Fn.dhall).CfnText
  , NielsenId3Behavior = None (./../../Fn.dhall).CfnText
  , NullPacketBitrate = None Double
  , PatInterval = None Integer
  , PcrControl = None (./../../Fn.dhall).CfnText
  , PcrPeriod = None Integer
  , PcrPid = None (./../../Fn.dhall).CfnText
  , PmtInterval = None Integer
  , PmtPid = None (./../../Fn.dhall).CfnText
  , ProgramNum = None Integer
  , RateMode = None (./../../Fn.dhall).CfnText
  , Scte27Pids = None (./../../Fn.dhall).CfnText
  , Scte35Control = None (./../../Fn.dhall).CfnText
  , Scte35Pid = None (./../../Fn.dhall).CfnText
  , SegmentationMarkers = None (./../../Fn.dhall).CfnText
  , SegmentationStyle = None (./../../Fn.dhall).CfnText
  , SegmentationTime = None Double
  , TimedMetadataBehavior = None (./../../Fn.dhall).CfnText
  , TimedMetadataPid = None (./../../Fn.dhall).CfnText
  , TransportStreamId = None Integer
  , VideoPid = None (./../../Fn.dhall).CfnText
  }
}